### PR TITLE
Initiate Error Handler, Fix for no LastModifiedDate, Fix for private mode (+ localStorage), Store + Restore SignParams

### PR DESCRIPTION
**Pull request by SamPotts**
Here you go. I've merged v1.0.0 and added the code to parse the AWS error code on initiate error. I noticed it's now a `me.warn()` rather than `me.error()` (makes sense, given we're retrying now). Also added some missing semi colons and a missing `var` (jshint warnings).

### CODE REVIEW

**Comment by SamPotts** [comment]
You can ignore the first 3 commits from previous requests. I reverted those changes (as the diff will show) and just used yours.

**Comment by SamPotts** [comment]
More info about the more recent changes here:
https://github.com/TTLabs/EvaporateJS/issues/115

**Comment by bikeath1337** [comment]
Hi, @SamPotts , is there something here to merge or did we add it in the last release? I tried to decode the changes amongst the whitespace fixes and am not sure if we covered this or not.

If we still need to consider this, if you could bring the branch current with master, that will make life easier! Many thanks.

**Comment by bikeath1337** [comment]
@SamPotts do we still have a merge candidate in this PR?

**Comment by SamPotts** [comment]
Well the only change I added previously was to make get the error code from the AWS response when initiate fails. 

```javascript 
var code = nodeValue(parseXml(xhr.response).getElementsByTagName('Error')[0], 'Code');                  
me.warn('Error initiating upload: ' + code);
```

That said, now that it appears to retry, this might be less of an issue. How many times does it retry? Is it never ending?

**Comment by bikeath1337** [comment]
It's a never-ending story. Fortunately, that's how we discovered the memory leak...let it retry all night and voila. :)

Should we close this, then?

**Comment by SamPotts** [comment]
Sure, will do.

**Pull request closed without merging**
