### PR TITLE
Allows signerUrl to be undefined, enabling signResponseHandler to sign requests

### PR DESCRIPTION
**Pull request by bikeath1337**
This is a convenience so that customers who already have custom signing algorithms can avoid an unnecessary call to signerUrl.

This PR also attempts to clarify how Evaporate can be configured to sign requests, illustrating that there is no longer a requirement to use `signerUrl` for customers with advanced authentication needs.

Note that the AWS lambda support probably could be simplified now.

### CODE REVIEW

**Comment by bikeath1337** [comment]
@jakubzitny I think this is a bit cleaner. I moved the check for signerUrl after the optimization that looks for an existing xhr.

**Comment by jakubzitny** [comment]
Thanks @bikeath1337, this looks great and way cleaner.. Let me try it out.

**Comment by jakubzitny** [comment]
Lgtm, works great, I am pro-merging.

**Comment by bikeath1337** [comment]
Thanks very much @jakubzitny

**Pull request merged**
