### PR TITLE
Allows AWS_KEY to be set per file added

### PR DESCRIPTION
**Pull request by HugoCrd**
Related to #309 
I removed `aws_key` from `IMMUTABLE_OPTIONS`.
I added one test, tell me if you want to see more tests here.

### CODE REVIEW

**Comment by bikeath1337** [comment]
Thank you @HugoCrd . The rest of the override validation takes place in `test/aws_url.spec.js`. I'd like to ask you to move your spec there, perhaps in the same spot I placed mine, so that similar features are tested together.

Or..we can refactor the override logic into a new file.

**Comment by HugoCrd** [comment]
We could rename aws_url.spec.js into aws_config.spec.js like in my last commit. If you got a better name let me know.
What do you think?

**Comment by bikeath1337** [comment]
@HugoCrd thank you so much for this contribution and for refactoring the specs. I brought this branch current with master and then added a commit to restore the aws_url spec I had added just before merging. I also removed a relic from the development where I has left in a "only" in my specs.

**Comment by HugoCrd** [comment]
Thanks for merging it ;)

**Pull request closed without merging**
