### PR TITLE
Fall back to anchor tag if window.URL fails

### PR DESCRIPTION
**Pull request by ryansydnor**
Addresses #325

### CODE REVIEW

**Comment by bikeath1337** [comment]
So IE defines URL but doesn't support it?

**Comment by ryansydnor** [comment]
Looks like it...

image

**Comment by ryansydnor** [comment]
What prompted the upgrade to `URL` initially? What do we lose if we fall back?

**Comment by bikeath1337** [comment]
We're trying to allow Evaporate to work in enviornments that don't have browser features: node.js, web workers and electron, for example.

Let me look at this this weekend in my windows virtual machine.

**Comment by ryansydnor** [comment]
👍

**Pull request merged**
