### PR TITLE
Formatting and Initiate Error Handler

### PR DESCRIPTION
**Pull request by SamPotts**
As discussed, first commit is purely white space and formatting changes. Second will be the error handler change.

### CODE REVIEW

**Comment by SamPotts** [comment]
This comparison of the uglified JavaScript may be more useful to check the formatting/jshint changes given the diff suggest a lot was changed:
https://www.diffchecker.com/fcg5iqtm

A couple of spots where arguments were removed was simply because they weren't being used. 

Let me know.

**Comment by bikeath1337** [comment]
@SamPotts now that master is updated, I need you to bring this branch current. Might make sense to just apply you changes to the error handler.

I tried rebasing this but there be lots 'o conflicts naturally.

**Comment by SamPotts** [comment]
Alright cool yeah, the formatting stuff was just me being picky any how and just fixing jshint warnings which may be resolved now anyway.

**Comment by bikeath1337** [comment]
At some point not too far away, I was going to clean up that stuff, too, but now I have to get back to my day job.

**Comment by SamPotts** [comment]
I know the feeling don't worry. plyr.io kills all my time.

**Pull request closed without merging**
