### PR TITLE
Support for AWS S3 Transfer Acceleration

### PR DESCRIPTION
**Pull request by bikeath1337**
This PR incrementally enhanced EvaporateJS to support S3 transfer acceleration and addresses #149 .

### CODE REVIEW

**Comment by SamPotts** [comment]
Any idea when this will merge?

**Comment by bikeath1337** [comment]
I need feedback first that it actually works. It did for me… but I am fickle.

**Comment by SamPotts** [comment]
Fair enough. I gave it a quick test last night and it seemed to work. Will do some more today. It's awesome you've added it so quickly.

**Comment by bikeath1337** [comment]
Thanks, Sam!

**Pull request closed without merging**
