### PR TITLE
Replacing all single quotes instead of first instance in func s3Encod…

### PR DESCRIPTION
**Pull request by profsmallpine**
@bikeath1337 

https://github.com/TTLabs/EvaporateJS/issues/264

### CODE REVIEW

**Comment by bikeath1337** [comment]
Many thanks. I added coverage, too.

Are you using V2 yet?

**Comment by profsmallpine** [comment]
@bikeath1337 I was going to update today, but I ended up just patching `1.6.3` because time..

**Comment by bikeath1337** [comment]
@profsmallpine I merged this to tag 1.6.4, which is not published to node but can be referenced like so (or one of the npm variations):

```shell
npm install git://github.com/TTLabs/EvaporateJS.git#1.6.4
```

**Comment by profsmallpine** [comment]
@bikeath1337 Sweet, you are on it! Thanks 😀

**Pull request merged**
